version: 2
log-file: /tmp/efmlangserver.log.txt
log-level: 2
root-markers:
  - .git/
  - package.json
lint-debounce: 0.4s

tools:
  css-prettier: &css-prettier
    format-command: "./node_modules/.bin/prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser css"

  html-prettier: &html-prettier
    format-command: "./node_modules/.bin/prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser html"

  javascript-eslint: &javascript-eslint
    format-command: "npx --no-install prettier"
    lint-command: "npx --no-install eslint -f unix --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true

  json-fixjson: &json-fixjson
    format-command: "fixjson"

  json-jq: &json-jq
    lint-command: "jq ."

  json-prettier: &json-prettier
    format-command: "./node_modules/.bin/prettier ${--tab-width:tabWidth} --parser json"

  lua-lua-format: &lua-lua-format
    format-command: "lua-format -i"
    format-stdin: true

  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s -c %USERPROFILE%\.markdownlintrc'
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"
      - "%f:%l:%c %m"
      - "%f: %l: %m"

  markdown-pandoc: &markdown-pandoc
    format-command: "pandoc -f markdown -t gfm -sp --tab-stop=2"

languages:
  css:
    - <<: *css-prettier

  html:
    - <<: *html-prettier

  javascript:
    - <<: *javascript-eslint

  typescript:
    - <<: *javascript-eslint

  typescriptreact:
    - <<: *javascript-eslint

  javascriptreact:
    - <<: *javascript-eslint

  json:
    - <<: *json-fixjson
    - <<: *json-jq
    # - <<: *json-prettier

  lua:
    - <<: *lua-lua-format

  markdown:
    - <<: *markdown-markdownlint
    - <<: *markdown-pandoc
