import = ["/home/jaye/.config/base16-alacritty/colors/base16-material.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Fira Code"
style = "Regular"

[[keyboard.bindings]]
key = "N"
mods = "Command"

[keyboard.bindings.command]
args = ["-n", "/Applications/Alacritty.app"]
program = "open"
